version: "3"
services:
  postgres:
    image: postgres:15.1
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
    - "5432:5432"
  graphql-api:
    build: 
      context: ./graphql-server
    depends_on:
      - postgres
    volumes:
      - ./graphql-server:/graphql-server
    environment:
      NODE_ENV: development
      PG_CONNECTION_STRING: postgres://postgres:postgrespassword@host.docker.internal:5432/postgres 
    ports: ['4000:4000'] 
volumes:
  db:
    driver: local
