federation_version: 2
subgraphs:
  cart:
    routing_url: http://localhost:9080/
    schema:
      subgraph_url: http://localhost:9080/
  cart_items:
    routing_url: http://localhost:9090/
    schema:
      subgraph_url: http://localhost:9090/